### ISSUE TITLE
Decide for Frontend framework

### ISSUE THREAD

**Issue by supernoir** [supernoir/periodicum#1]
Angular - I already created a bunch of projects already in Angular, would be quick to setup
React - I would be interested in learning the  framework

**Comment by lisbethmarianne** [comment]
I would be interested in learning both but lets go React because some RGSoC projects have that maybe we can benefit from learning a bit about it. (Maybe we take a React project as our second choice.)

**Comment by supernoir** [comment]
Sounds good. I would also love to try React out for this one :)
