### ISSUE TITLE
Setup repo and start package.json with dev dependencies

### ISSUE THREAD

**Issue by supernoir** [supernoir/periodicum#2]

**Comment by lisbethmarianne** [comment]
Can you write some short notes, what you did? I'm trying to remember but it was to fast. Thanks!

**Comment by supernoir** [comment]
Sure thing.

---

### Create new local and remote repo
- create new project folder (mkdir foldername)
- git init (Initiates New Git Repository)
- git add . (Adds all files/folders to the new repo)
- git commit -m "First Commit" (adds first commit with message)
- go to github, create new repo, copy the link to remote repo
- back in terminal, git add remote origin https://github.com/username/repositoryname.git (with the link you have copied)
- git push origin master

---

### Create new Node Project with Dependencies using NPM
- npm init (helps to fill out the package.json interactively)
- npm install node --save (installs node and "saves" the installation to the json)
- npm install express --save (installs expressjs and saves to json)
- you should now have a new folder called node_modules and a package.json file with dependencies
- create new file (e.g. touch filename) server.js
- add this to the file to start a simple server listening on a port of your choice:
- \- 'use strict' (for strict mode)
- \- var express = require('express');
- \- var app = express();
- \- var port = 8787;
- \- app.listen(port);
- \- console.log('Server is running at port ' + port);
- And this should do it! :)
