### ISSUE TITLE
create content for element detail view in JSON

### ISSUE THREAD

**Issue by supernoir** [supernoir/periodicum#28]
The detail view contains at least the name, symbol, atom number etc, but also an image to illustrate the element and a short text. It should be stored in a JSON

**Comment by lisbethmarianne** [comment]
Added some text everywhere (first paragraph from wikipedia). 
Most of the elements also have pictures (link to wikipedia) and a description of the image. Some element pictures are missing (radioactive elements, ...).

See PR #31

**Comment by supernoir** [comment]
Optimize
